# Docker Compose (v2)

version: "2"
services:

  hub:
    image: drupalcomposer/selenium:hub
    ports:
      - "4444:4444"
    network:
      - hub

  firefox:
    image: drupalcomposer/selenium:node-firefox
    network:
      - hub

  networks:
    hub:
